Hello.class : Hello.java
	javac Hello.java
Printer.class : Printer.java
	javac Printer.java
Hello.java : Printer.java
run : Hello.class
	java -cp . Hello
build : Hello.java
	javac Hello.java
clean : 
	del C:\Users\User\Documents\NewTestGit\team14\0-helloex\*.class